package checks

import "github.com/varax/operator/pkg/scanning"

// RegisterAll registers all built-in CIS checks with the given registry.
func RegisterAll(r *scanning.Registry) {
	// API server checks (1.2.x)
	r.Register(&AnonAuthCheck{})
	r.Register(&TokenAuthCheck{})
	r.Register(&DenyServiceExternalIPsCheck{})
	r.Register(&KubeletClientCertCheck{})
	r.Register(&KubeletCACheck{})
	r.Register(&NoAlwaysAllowCheck{})
	r.Register(&NodeAuthCheck{})
	r.Register(&RBACAuthCheck{})
	r.Register(&EventRateLimitCheck{})
	r.Register(&AlwaysPullImagesCheck{})
	r.Register(&SecurityContextAdmissionCheck{})
	r.Register(&ServiceAccountAdmissionCheck{})
	r.Register(&NamespaceLifecycleCheck{})
	r.Register(&NodeRestrictionCheck{})
	r.Register(&APIServerProfilingCheck{})
	r.Register(&AuditLogPathCheck{})
	r.Register(&AuditLogMaxAgeCheck{})
	r.Register(&AuditLogMaxBackupCheck{})
	r.Register(&AuditLogMaxSizeCheck{})
	r.Register(&RequestTimeoutCheck{})
	r.Register(&SALookupCheck{})
	r.Register(&SAKeyFileCheck{})
	r.Register(&EtcdCertCheck{})
	r.Register(&TLSCertCheck{})
	r.Register(&ClientCACheck{})
	r.Register(&EtcdCACheck{})

	// Controller manager checks (1.3.x)
	r.Register(&CMTerminatedPodGCCheck{})
	r.Register(&CMProfilingCheck{})
	r.Register(&CMSACredentialsCheck{})
	r.Register(&CMSAPrivateKeyCheck{})
	r.Register(&CMRootCACheck{})
	r.Register(&CMRotateKubeletCertCheck{})
	r.Register(&CMBindAddressCheck{})

	// Scheduler checks (1.4.x)
	r.Register(&SchedulerProfilingCheck{})
	r.Register(&SchedulerBindAddressCheck{})

	// etcd checks (2.x)
	r.Register(&EtcdCertFileCheck{})
	r.Register(&EtcdClientCertAuthCheck{})
	r.Register(&EtcdAutoTLSCheck{})
	r.Register(&EtcdPeerCertCheck{})
	r.Register(&EtcdPeerClientCertAuthCheck{})
	r.Register(&EtcdPeerAutoTLSCheck{})
	r.Register(&EtcdUniqueCACheck{})

	// Control plane config checks (3.x)
	r.Register(&NoStaticTokensCheck{})
	r.Register(&AuditPolicyCheck{})

	// Kubelet checks (4.2.x)
	r.Register(KubeletAnonAuthCheck)
	r.Register(KubeletAuthModeCheck)
	r.Register(KubeletClientCertificateCheck)
	r.Register(KubeletReadOnlyPortCheck)
	r.Register(KubeletStreamingCheck)
	r.Register(KubeletProtectKernelDefaultsCheck)
	r.Register(KubeletIPTablesCheck)
	r.Register(KubeletHostnameOverrideCheck)
	r.Register(KubeletEventQPSCheck)
	r.Register(KubeletTLSCertCheck)
	r.Register(KubeletTLSKeyCheck)
	r.Register(KubeletRotateCertCheck)
	r.Register(KubeletIntegrityCheck)

	// RBAC checks (5.1.x)
	r.Register(&ClusterAdminCheck{})
	r.Register(&SecretAccessCheck{})
	r.Register(&WildcardRBACCheck{})
	r.Register(&DefaultServiceAccountCheck{})
	r.Register(&SATokenAutoMountCheck{})
	r.Register(&EscalatePermsCheck{})
	r.Register(&NamespaceBoundariesCheck{})
	r.Register(&SystemMastersCheck{})

	// Pod security checks (5.2.x)
	r.Register(&PrivilegeEscalationCheck{})
	r.Register(&RootContainerCheck{})
	r.Register(&PrivilegedContainerCheck{})
	r.Register(&DropCapabilitiesCheck{})
	r.Register(&HostPIDCheck{})
	r.Register(&HostIPCCheck{})
	r.Register(&HostNetworkCheck{})
	r.Register(&HostPortCheck{})
	r.Register(&AddedCapabilitiesCheck{})
	r.Register(&ProcMountCheck{})
	r.Register(&HostProcessCheck{})
	r.Register(&AppArmorCheck{})
	r.Register(&SysctlsCheck{})

	// Network policy checks (5.3.x)
	r.Register(&CNINetworkPolicyCheck{})
	r.Register(&NetworkPolicyCheck{})

	// Secret management checks (5.4.x)
	r.Register(&SecretEnvVarCheck{})

	// General security checks (5.7.x)
	r.Register(&SeccompCheck{})
	r.Register(&SecurityContextCheck{})
	r.Register(&DefaultNamespaceCheck{})
	r.Register(&NamespaceLimitsCheck{})
}
