//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertsSpec) DeepCopyInto(out *AlertsSpec) {
	*out = *in
	if in.ScoreThreshold != nil {
		in, out := &in.ScoreThreshold, &out.ScoreThreshold
		*out = new(int)
		**out = **in
	}
	if in.CriticalViolations != nil {
		in, out := &in.CriticalViolations, &out.CriticalViolations
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertsSpec.
func (in *AlertsSpec) DeepCopy() *AlertsSpec {
	if in == nil {
		return nil
	}
	out := new(AlertsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuditLoggingSpec) DeepCopyInto(out *AuditLoggingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuditLoggingSpec.
func (in *AuditLoggingSpec) DeepCopy() *AuditLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(AuditLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceConfig) DeepCopyInto(out *ComplianceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceConfig.
func (in *ComplianceConfig) DeepCopy() *ComplianceConfig {
	if in == nil {
		return nil
	}
	out := new(ComplianceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceConfigList) DeepCopyInto(out *ComplianceConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceConfigList.
func (in *ComplianceConfigList) DeepCopy() *ComplianceConfigList {
	if in == nil {
		return nil
	}
	out := new(ComplianceConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceConfigSpec) DeepCopyInto(out *ComplianceConfigSpec) {
	*out = *in
	in.Controls.DeepCopyInto(&out.Controls)
	in.Scanning.DeepCopyInto(&out.Scanning)
	out.AuditLogging = in.AuditLogging
	out.Remediation = in.Remediation
	in.Reports.DeepCopyInto(&out.Reports)
	in.Alerts.DeepCopyInto(&out.Alerts)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceConfigSpec.
func (in *ComplianceConfigSpec) DeepCopy() *ComplianceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceConfigStatus) DeepCopyInto(out *ComplianceConfigStatus) {
	*out = *in
	if in.LastScanTime != nil {
		in, out := &in.LastScanTime, &out.LastScanTime
		*out = (*in).DeepCopy()
	}
	if in.FrameworkStatus != nil {
		in, out := &in.FrameworkStatus, &out.FrameworkStatus
		*out = make([]FrameworkStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceConfigStatus.
func (in *ComplianceConfigStatus) DeepCopy() *ComplianceConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlsSpec) DeepCopyInto(out *ControlsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlsSpec.
func (in *ControlsSpec) DeepCopy() *ControlsSpec {
	if in == nil {
		return nil
	}
	out := new(ControlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrameworkStatus) DeepCopyInto(out *FrameworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrameworkStatus.
func (in *FrameworkStatus) DeepCopy() *FrameworkStatus {
	if in == nil {
		return nil
	}
	out := new(FrameworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationSpec) DeepCopyInto(out *RemediationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationSpec.
func (in *RemediationSpec) DeepCopy() *RemediationSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReportsSpec) DeepCopyInto(out *ReportsSpec) {
	*out = *in
	if in.Formats != nil {
		in, out := &in.Formats, &out.Formats
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReportsSpec.
func (in *ReportsSpec) DeepCopy() *ReportsSpec {
	if in == nil {
		return nil
	}
	out := new(ReportsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanningSpec) DeepCopyInto(out *ScanningSpec) {
	*out = *in
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanningSpec.
func (in *ScanningSpec) DeepCopy() *ScanningSpec {
	if in == nil {
		return nil
	}
	out := new(ScanningSpec)
	in.DeepCopyInto(out)
	return out
}
